/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTrendsRouteImport } from './routes/app.trends'
import { Route as AppScoreRouteImport } from './routes/app.score'
import { Route as AppProveRouteImport } from './routes/app.prove'
import { Route as AppOpportunitiesRouteImport } from './routes/app.opportunities'
import { Route as AppModelsRouteImport } from './routes/app.models'
import { Route as AppMeasureRouteImport } from './routes/app.measure'
import { Route as AppLoginRouteImport } from './routes/app.login'
import { Route as AppListenRouteImport } from './routes/app.listen'
import { Route as AppHowItWorksRouteImport } from './routes/app.how-it-works'
import { Route as AppCreateRouteImport } from './routes/app.create'
import { Route as AppChannelsRouteImport } from './routes/app.channels'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTrendsRoute = AppTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => AppRoute,
} as any)
const AppScoreRoute = AppScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => AppRoute,
} as any)
const AppProveRoute = AppProveRouteImport.update({
  id: '/prove',
  path: '/prove',
  getParentRoute: () => AppRoute,
} as any)
const AppOpportunitiesRoute = AppOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => AppRoute,
} as any)
const AppModelsRoute = AppModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AppRoute,
} as any)
const AppMeasureRoute = AppMeasureRouteImport.update({
  id: '/measure',
  path: '/measure',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppListenRoute = AppListenRouteImport.update({
  id: '/listen',
  path: '/listen',
  getParentRoute: () => AppRoute,
} as any)
const AppHowItWorksRoute = AppHowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateRoute = AppCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsRoute = AppChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/channels': typeof AppChannelsRoute
  '/app/create': typeof AppCreateRoute
  '/app/how-it-works': typeof AppHowItWorksRoute
  '/app/listen': typeof AppListenRoute
  '/app/login': typeof AppLoginRoute
  '/app/measure': typeof AppMeasureRoute
  '/app/models': typeof AppModelsRoute
  '/app/opportunities': typeof AppOpportunitiesRoute
  '/app/prove': typeof AppProveRoute
  '/app/score': typeof AppScoreRoute
  '/app/trends': typeof AppTrendsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/channels': typeof AppChannelsRoute
  '/app/create': typeof AppCreateRoute
  '/app/how-it-works': typeof AppHowItWorksRoute
  '/app/listen': typeof AppListenRoute
  '/app/login': typeof AppLoginRoute
  '/app/measure': typeof AppMeasureRoute
  '/app/models': typeof AppModelsRoute
  '/app/opportunities': typeof AppOpportunitiesRoute
  '/app/prove': typeof AppProveRoute
  '/app/score': typeof AppScoreRoute
  '/app/trends': typeof AppTrendsRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/channels': typeof AppChannelsRoute
  '/app/create': typeof AppCreateRoute
  '/app/how-it-works': typeof AppHowItWorksRoute
  '/app/listen': typeof AppListenRoute
  '/app/login': typeof AppLoginRoute
  '/app/measure': typeof AppMeasureRoute
  '/app/models': typeof AppModelsRoute
  '/app/opportunities': typeof AppOpportunitiesRoute
  '/app/prove': typeof AppProveRoute
  '/app/score': typeof AppScoreRoute
  '/app/trends': typeof AppTrendsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/channels'
    | '/app/create'
    | '/app/how-it-works'
    | '/app/listen'
    | '/app/login'
    | '/app/measure'
    | '/app/models'
    | '/app/opportunities'
    | '/app/prove'
    | '/app/score'
    | '/app/trends'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/channels'
    | '/app/create'
    | '/app/how-it-works'
    | '/app/listen'
    | '/app/login'
    | '/app/measure'
    | '/app/models'
    | '/app/opportunities'
    | '/app/prove'
    | '/app/score'
    | '/app/trends'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/channels'
    | '/app/create'
    | '/app/how-it-works'
    | '/app/listen'
    | '/app/login'
    | '/app/measure'
    | '/app/models'
    | '/app/opportunities'
    | '/app/prove'
    | '/app/score'
    | '/app/trends'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/trends': {
      id: '/app/trends'
      path: '/trends'
      fullPath: '/app/trends'
      preLoaderRoute: typeof AppTrendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/score': {
      id: '/app/score'
      path: '/score'
      fullPath: '/app/score'
      preLoaderRoute: typeof AppScoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/prove': {
      id: '/app/prove'
      path: '/prove'
      fullPath: '/app/prove'
      preLoaderRoute: typeof AppProveRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/opportunities': {
      id: '/app/opportunities'
      path: '/opportunities'
      fullPath: '/app/opportunities'
      preLoaderRoute: typeof AppOpportunitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/models': {
      id: '/app/models'
      path: '/models'
      fullPath: '/app/models'
      preLoaderRoute: typeof AppModelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/measure': {
      id: '/app/measure'
      path: '/measure'
      fullPath: '/app/measure'
      preLoaderRoute: typeof AppMeasureRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/login': {
      id: '/app/login'
      path: '/login'
      fullPath: '/app/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/listen': {
      id: '/app/listen'
      path: '/listen'
      fullPath: '/app/listen'
      preLoaderRoute: typeof AppListenRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/how-it-works': {
      id: '/app/how-it-works'
      path: '/how-it-works'
      fullPath: '/app/how-it-works'
      preLoaderRoute: typeof AppHowItWorksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/create': {
      id: '/app/create'
      path: '/create'
      fullPath: '/app/create'
      preLoaderRoute: typeof AppCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/channels': {
      id: '/app/channels'
      path: '/channels'
      fullPath: '/app/channels'
      preLoaderRoute: typeof AppChannelsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppChannelsRoute: typeof AppChannelsRoute
  AppCreateRoute: typeof AppCreateRoute
  AppHowItWorksRoute: typeof AppHowItWorksRoute
  AppListenRoute: typeof AppListenRoute
  AppLoginRoute: typeof AppLoginRoute
  AppMeasureRoute: typeof AppMeasureRoute
  AppModelsRoute: typeof AppModelsRoute
  AppOpportunitiesRoute: typeof AppOpportunitiesRoute
  AppProveRoute: typeof AppProveRoute
  AppScoreRoute: typeof AppScoreRoute
  AppTrendsRoute: typeof AppTrendsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChannelsRoute: AppChannelsRoute,
  AppCreateRoute: AppCreateRoute,
  AppHowItWorksRoute: AppHowItWorksRoute,
  AppListenRoute: AppListenRoute,
  AppLoginRoute: AppLoginRoute,
  AppMeasureRoute: AppMeasureRoute,
  AppModelsRoute: AppModelsRoute,
  AppOpportunitiesRoute: AppOpportunitiesRoute,
  AppProveRoute: AppProveRoute,
  AppScoreRoute: AppScoreRoute,
  AppTrendsRoute: AppTrendsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
